### PR TITLE
Bump chromedriver dev dependency to 95.0.0

### PR DESCRIPTION
**Pull request by gianantoniopini**
This pull request upgrades the chromedriver dev dependency from version 94.0.0 to 95.0.0.
This is to make chromedriver compatible with the current Chrome version and avoid warnings when running tests.

It also includes the fix for a failing test in the test-form spec.

### CODE REVIEW

**Comment by gianantoniopini** [comment]
There is a test failing. Checking this...

**Comment by gianantoniopini** [comment]
The failing test has been fixed.

**Comment by yoavaviram** [comment]
Thanks @gianantoniopini

**Comment by gianantoniopini** [comment]
Hi @yoavaviram , thanks for merging this.

**Pull request merged**
