### PR TITLE
Style amends

### PR DESCRIPTION
**Pull request by roughprada**
I have made a bunch of updates on style and some components that were configured wrongly, including the FAQs

### CODE REVIEW

**Comment by yoavaviram** [comment]
@roughprada can you please pull from master first?

**Comment by roughprada** [comment]
@yoavaviram The only missing updates that I see are coming from Crowdin, but I've merged now.
There are some CricleCI errors, but not sure what to do there.

**Comment by yoavaviram** [comment]
@roughprada not sure what happened here. I can see that you overwrote some important bits, for example the 'contribute' nav item is gone. Can you take a look?

**Comment by roughprada** [comment]
@yoavaviram Certainly weird! I think is back now :)

**Review by honzie — APPROVED** [review]
Awesome! Thanks for making these changes; especially the global link color update.

**Comment by honzie** [comment]
@yoavaviram @roughprada : Looks like contribute was moved to a sub item when in the dropdown menu. Was this intentional? If so, I can help update the tests.

**Comment by yoavaviram** [comment]
Looks ok now. One last comment: @roughprada  the language selector is not horizontally aligned with the rest of the nav items

**Comment by honzie** [comment]
"the language selector is not horizontally aligned with the rest of the nav items": I've addressed this and some other nav concerns (super minor stuff) in https://github.com/your-digital-rights/yourdigitalrights.org/pull/242

**Comment by roughprada** [comment]
epic, thanks for all the test and changes peeps! happy  to merge if  you are @yoavaviram

**Pull request merged**
