### PR TITLE
Fix tests and bug with search input focus

### LINKED ISSUE #130: [Nav] When clicking on the search button, the search bar is not focused and ready to type in it.

### LINKED ISSUE #158: Tests are failing
The tests appear to be broken: running "npm test" does not work for me.

It seems that the tests code needs to be updated to reflect the latest app changes. Also it seems that some dev dependencies required to run the tests are missing, for example the WebdriverIO packages.

I have started looking into this on my fork.

### PR DESCRIPTION
**Pull request by gianantoniopini**
Fixes #158 :
- added dev dependencies for WebdriverIO and chromedriver
- tests updated to use the latest version of WebdriverIO and to reflect the current version of the app
- WebdriverIO configuration changed to use chromedriver (instead of selenium-standalone) test runner service
- grouped all tests related to navigation into new test-nav.js file

---

Fixes #130 :
- using new #searchOrganizations url anchor to enable transition to #hero url anchor and set the focus on the Search input
- added new tests for all different scenarios in which the Search input should be focused

---

Other:
- updated the fetchData function in sheets.js to check for response status and throw an error in case of unsuccessful response

### CODE REVIEW

**Comment by gianantoniopini** [comment]
@yoavaviram Can you please have a look at this pull request ?

**Comment by yoavaviram** [comment]
Hi @gianantoniopini , sorry for not replying to your earlier messages. Thank you for contributing and for the willingness to pick up the broken tests! Much appreciated. I'll review the PR shortly.

**Comment by gianantoniopini** [comment]
Hi @yoavaviram , no problem at all. Thanks 👍

**Comment by yoavaviram** [comment]
Amazing work @gianantoniopini !  I just merged and deployed this to production.

If you'd like to contribute further let me know, there are plenty of things that need to be done of all shapes and sizes.

**Comment by gianantoniopini** [comment]
Grazie @yoavaviram . Very glad to know that this PR could be useful. Thanks for reviewing it. And it is nice to see the tests now passing on CircleCI :-)
I was already thinking to try and work on some other issues in this useful project, so yes I'd like to contribute further.

**Pull request merged**
